/** Rapor Yönetimi kartları — tek kaynak (DB `rapor_tanim` ile senkron tutulur). */
export interface RaporTanim {
  kod: string
  slug: string
  href: string
  baslik: string
  aciklama: string
  renk: string
  olusturulma_tarihi: string
  /** Kalıcı kapsam ayarı veya excel aralığı gibi değişebilen kapsam türü */
  kapsam_tipi: 'ayar_liste' | 'excel_aralik' | 'yok'
}

export const RAPOR_TANIMLARI: RaporTanim[] = [
  { kod: 'IHR', slug: 'izin-hareketleri', href: '/rapor/izin-hareketleri', baslik: 'İzin Hareketleri Raporu', aciklama: 'İki sıra numarası aralığına göre izin hareketlerini salt okunur görüntüleyip Excel indirebilirsiniz', renk: 'border-teal-200 bg-teal-50 text-teal-900', olusturulma_tarihi: '2026-01-10', kapsam_tipi: 'excel_aralik' },
  { kod: 'MIR', slug: 'memur-izinleri', href: '/rapor/memur-izinleri', baslik: 'Memur İzinleri Raporu', aciklama: 'Memur statüsündeki personeller için izin hakkı, kullanılan izin ve kalan izin bilgisi', renk: 'border-blue-200 bg-blue-50 text-blue-900', olusturulma_tarihi: '2026-06-01', kapsam_tipi: 'yok' },
  { kod: 'IIR', slug: 'isci-izinleri', href: '/rapor/isci-izinleri', baslik: 'İşçi İzinleri Raporu', aciklama: 'İşçi statüsündeki personeller için izin hakkı, kullanılan izin ve kalan izin bilgisi', renk: 'border-emerald-200 bg-emerald-50 text-emerald-900', olusturulma_tarihi: '2026-06-01', kapsam_tipi: 'yok' },
  { kod: 'SGC', slug: 'statuye-gore-cinsiyet', href: '/rapor/statuye-gore-cinsiyet', baslik: 'Statüye Göre Cinsiyet Raporu', aciklama: 'YILLIK ve Ocak–Aralık sekmeleri; kadın/erkek dağılımı ve gelen/ayrılan özetleri', renk: 'border-cyan-200 bg-cyan-50 text-cyan-900', olusturulma_tarihi: '2026-01-15', kapsam_tipi: 'yok' },
  { kod: 'SGS', slug: 'statuye-gore-sayi', href: '/rapor/statuye-gore-sayi', baslik: 'Statüye Göre Sayı Durumu Raporu', aciklama: 'Statü başına toplam personel sayısı; aynı dönem ve gelen/ayrılan özetleri', renk: 'border-sky-200 bg-sky-50 text-sky-900', olusturulma_tarihi: '2026-01-15', kapsam_tipi: 'yok' },
  { kod: 'SGY', slug: 'statuye-gore-yas', href: '/rapor/statuye-gore-yas', baslik: 'Statüye Göre Yaş Raporu', aciklama: 'Yaş aralıklarına göre dağılım; doğum yılından hesaplanan yaş ve dönem özetleri', renk: 'border-indigo-200 bg-indigo-50 text-indigo-900', olusturulma_tarihi: '2026-01-15', kapsam_tipi: 'yok' },
  { kod: 'SGH', slug: 'statuye-gore-hizmet', href: '/rapor/statuye-gore-hizmet', baslik: 'Statüye Göre Hizmet Raporu', aciklama: 'Hizmet süresi aralıklarına göre dağılım; 360 gün esaslı yıl/ay/gün verilerinden hesaplanır', renk: 'border-emerald-200 bg-emerald-50 text-emerald-900', olusturulma_tarihi: '2026-01-15', kapsam_tipi: 'yok' },
  { kod: 'KGC', slug: 'konuma-gore-cinsiyet', href: '/rapor/konuma-gore-cinsiyet', baslik: 'Konuma Göre Cinsiyet Raporu', aciklama: 'Tanımlar > Müdürlük yerleşke eşlemesindeki İç/Dış konumuna göre kadın/erkek; aynı sekme ve özet yapısı', renk: 'border-violet-200 bg-violet-50 text-violet-900', olusturulma_tarihi: '2026-02-01', kapsam_tipi: 'yok' },
  { kod: 'YGP', slug: 'yerleske-adresine-gore-personel-sayi', href: '/rapor/yerleske-adresine-gore-personel-sayi', baslik: 'Yerleşke Adresine Göre Personel Sayısı', aciklama: 'Müdürlük–yerleşke satırlarında ADABEL ve belediye personeli sayıları; YILLIK ve aylık sekmeler', renk: 'border-indigo-200 bg-indigo-50 text-indigo-900', olusturulma_tarihi: '2026-02-01', kapsam_tipi: 'yok' },
  { kod: 'SGO', slug: 'statuye-gore-ogrenim', href: '/rapor/statuye-gore-ogrenim', baslik: 'Statüye Göre Öğrenim Durumu Raporu', aciklama: 'Varsayılan öğrenim (kadro) ve firma kartı öğrenimi; Tanımlar > Öğrenim ve Statü sütunları', renk: 'border-blue-200 bg-blue-50 text-blue-900', olusturulma_tarihi: '2026-01-20', kapsam_tipi: 'yok' },
  { kod: 'SGM', slug: 'statuye-gore-meslek', href: '/rapor/statuye-gore-meslek', baslik: 'Statüye Göre Meslek Raporu', aciklama: 'Öğrenim kaydındaki meslek (kadro) ve firma meslek alanı; matris ve dönem özetleri', renk: 'border-purple-200 bg-purple-50 text-purple-900', olusturulma_tarihi: '2026-01-20', kapsam_tipi: 'yok' },
  { kod: 'MSL', slug: 'meslek-sahibi-liste', href: '/rapor/meslek-sahibi-liste', baslik: 'Meslek Sahibi Personel Listesi', aciklama: 'YILLIK ve Ocak–Aralık; sicil, ad soyad ve meslek adı (anlık görüntü)', renk: 'border-amber-200 bg-amber-50 text-amber-900', olusturulma_tarihi: '2026-01-20', kapsam_tipi: 'yok' },
  { kod: 'GYL', slug: 'gorev-yerine-gore-liste', href: '/rapor/gorev-yerine-gore-liste', baslik: 'Görev Yerine Göre Personel Listesi', aciklama: 'Konum, cinsiyet, unvan, statü ve fiili görev (Görev Bilgileri ile uyumlu anlık görüntü)', renk: 'border-rose-200 bg-rose-50 text-rose-900', olusturulma_tarihi: '2026-04-27', kapsam_tipi: 'ayar_liste' },
  { kod: 'MPL', slug: 'mudurluge-gore-personel-liste', href: '/rapor/mudurluge-gore-personel-liste', baslik: 'Müdürlüğe Göre Personel Listesi', aciklama: 'Kadro müdürlüğüne göre alfabetik, müdürlük içinde sicil artan sıralı personel listesi', renk: 'border-lime-200 bg-lime-50 text-lime-900', olusturulma_tarihi: '2026-03-01', kapsam_tipi: 'yok' },
  { kod: 'TSM', slug: 'tehlike-siniflarina-gore-mudurluk', href: '/rapor/tehlike-siniflarina-gore-mudurluk', baslik: 'Tehlike Sınıflarına Göre Müdürlük Raporu', aciklama: 'Müdürlük tehlike sınıfına göre personel sayısı özeti (ADABEL hariç).', renk: 'border-orange-200 bg-orange-50 text-orange-900', olusturulma_tarihi: '2026-03-01', kapsam_tipi: 'yok' },
  { kod: 'TML', slug: 'tehlikeli-sinif-mudurluk-listesi', href: '/rapor/tehlikeli-sinif-mudurluk-listesi', baslik: 'Tehlike Sınıfına Göre Müdürlük Listesi', aciklama: 'Aktif müdürlükleri tehlike sınıfı önceliğine göre listeler.', renk: 'border-red-200 bg-red-50 text-red-900', olusturulma_tarihi: '2026-03-01', kapsam_tipi: 'yok' },
  { kod: 'TPL', slug: 'tehlikeli-sinif-personel-listesi', href: '/rapor/tehlikeli-sinif-personel-listesi', baslik: 'Tehlike Sınıfına Göre Personel Listesi', aciklama: 'Tehlike sınıfı, müdürlük ve sicil sırasına göre personel listesi (ADABEL hariç).', renk: 'border-rose-200 bg-rose-50 text-rose-900', olusturulma_tarihi: '2026-03-01', kapsam_tipi: 'yok' },
  { kod: 'KPL', slug: 'kan-grubuna-gore-personel-liste', href: '/rapor/kan-grubuna-gore-personel-liste', baslik: 'Kan Grubuna Göre Personel Listesi', aciklama: 'Kan grubu checkbox filtresiyle personel listesi; yıllık/aylık ve Excel destekli.', renk: 'border-cyan-200 bg-cyan-50 text-cyan-900', olusturulma_tarihi: '2026-03-10', kapsam_tipi: 'yok' },
  { kod: 'DGL', slug: 'dogum-gunune-gore-personel-liste', href: '/rapor/dogum-gunune-gore-personel-liste', baslik: 'Doğum Gününe Göre Personel Listesi', aciklama: 'Aylık sekmelerde ilgili ayda doğan aktif personellerin sicil ve ad soyad listesi.', renk: 'border-teal-200 bg-teal-50 text-teal-900', olusturulma_tarihi: '2026-03-10', kapsam_tipi: 'yok' },
  { kod: 'BPL', slug: 'belediye-geneli-personel-liste', href: '/rapor/belediye-geneli-personel-liste', baslik: 'Belediye Geneli Personel Listesi', aciklama: 'Kimlik, statü, unvan, müdürlük ve iletişim bilgileriyle belediye geneli aktif personel listesi', renk: 'border-fuchsia-200 bg-fuchsia-50 text-fuchsia-900', olusturulma_tarihi: '2026-04-01', kapsam_tipi: 'yok' },
  { kod: 'APL', slug: 'adabel-personel-bilgileri-liste', href: '/rapor/adabel-personel-bilgileri-liste', baslik: 'ADABEL Personel Bilgileri Listesi', aciklama: 'ADABEL personelinin sicil, kimlik, iletişim ve görev bilgileri; yıllık/aylık sekmeler ve Excel.', renk: 'border-amber-200 bg-amber-50 text-amber-900', olusturulma_tarihi: '2026-04-01', kapsam_tipi: 'yok' },
  { kod: 'YIB', slug: 'yonetici-iletisim-bilgileri-liste', href: '/rapor/yonetici-iletisim-bilgileri-liste', baslik: 'Yönetici İletişim Bilgileri Listesi', aciklama: 'Belediye Başkanı, Başkan Yardımcısı ve Müdür unvanlı kayıtlar için iletişim listesi', renk: 'border-slate-300 bg-slate-50 text-slate-900', olusturulma_tarihi: '2026-04-28', kapsam_tipi: 'ayar_liste' },
  { kod: 'YOD', slug: 'yonetici-ogrenim-durum-liste', href: '/rapor/yonetici-ogrenim-durum-liste', baslik: 'Yönetici Öğrenim Durum Listesi', aciklama: 'Görev unvanında Müdür ifadesi geçen personellerin öğrenim bilgilerinin tümü (sicil artan).', renk: 'border-indigo-200 bg-indigo-50 text-indigo-900', olusturulma_tarihi: '2026-04-01', kapsam_tipi: 'yok' },
  { kod: 'AGP', slug: 'adrese-gore-personel-liste', href: '/rapor/adrese-gore-personel-liste', baslik: 'Adrese Göre Personel Listesi', aciklama: 'Aktif personelin İl, İlçe ve Mahalle bilgisiyle listesi; il → ilçe → mahalle bazlı filtreleme ve Excel çıktısı.', renk: 'border-emerald-200 bg-emerald-50 text-emerald-900', olusturulma_tarihi: '2026-04-01', kapsam_tipi: 'yok' },
  { kod: 'ODP', slug: 'ogrenim-durumuna-gore-personel-liste', href: '/rapor/ogrenim-durumuna-gore-personel-liste', baslik: 'Öğrenim Durumuna Göre Personel Listesi', aciklama: 'Lisans + lisansüstü/doktora kaydı olan personelde kimlik sütunları birleştirilmiş öğrenim satırlarıyla listelenir.', renk: 'border-blue-200 bg-blue-50 text-blue-900', olusturulma_tarihi: '2026-04-15', kapsam_tipi: 'yok' },
  { kod: 'ODI', slug: 'ogrenim-durumuna-gore-iletisim-bilgileri-liste', href: '/rapor/ogrenim-durumuna-gore-iletisim-bilgileri-liste', baslik: 'Öğrenim Durumuna Göre İletişim Bilgileri Listesi', aciklama: 'Öğrenim durumuna göre personel listesine cep telefonu ve e-posta eklenir; YILLIK ve aylık sekmeler, müdürlük filtresi ve Excel.', renk: 'border-sky-200 bg-sky-50 text-sky-900', olusturulma_tarihi: '2026-07-10', kapsam_tipi: 'yok' },
  { kod: 'ILT', slug: 'izin-limitine-takilan-personel-liste', href: '/rapor/izin-limitine-takilan-personel-liste', baslik: 'İzin Limitine Takılan Personel Listesi', aciklama: 'Kullanılan izin toplamı yükseldikçe satır rengi kırmızı tona yaklaşan, filtrelenebilir yıllık/aylık personel listesi.', renk: 'border-red-200 bg-red-50 text-red-900', olusturulma_tarihi: '2026-04-15', kapsam_tipi: 'yok' },
  { kod: 'PGI', slug: 'personele-gore-kullanilan-izin-listesi', href: '/rapor/personele-gore-kullanilan-izin-listesi', baslik: 'Personele Göre Kullanılan İzin Listesi', aciklama: 'Müdürlük, sicil ve türe göre filtrelenebilir, başlıklarda sıralanabilir izin kayıt listesi; Excel destekli.', renk: 'border-teal-200 bg-teal-50 text-teal-900', olusturulma_tarihi: '2026-04-20', kapsam_tipi: 'yok' },
  { kod: 'BGI', slug: 'belirli-gunde-izinli-personel', href: '/rapor/belirli-gunde-izinli-personel', baslik: 'Belirli Günde İzinli Olan Personel Listesi', aciklama: 'Seçilen tarihte aktif izni devam eden personeli müdürlük, konum (İç/Dış) ve türe göre filtreli listeler; Excel destekli.', renk: 'border-violet-200 bg-violet-50 text-violet-900', olusturulma_tarihi: '2026-04-20', kapsam_tipi: 'yok' },
  { kod: 'MIM', slug: 'maas-oncesi-izinli-mudurler', href: '/rapor/maas-oncesi-izinli-mudurler', baslik: 'Maaş Öncesi İzinli Müdürler Raporu', aciklama: 'Her ayın 10–14. günlerinde izinli olan müdür unvanlı personeli sicil numarasına göre listeler; Yıllık/Aylık sekmesi ve Excel destekli.', renk: 'border-orange-200 bg-orange-50 text-orange-900', olusturulma_tarihi: '2026-04-22', kapsam_tipi: 'yok' },
  { kod: 'GTC', slug: 'gorev-turune-gore-calisan', href: '/rapor/gorev-turune-gore-calisan', baslik: 'Görev Türüne Göre Çalışan Bilgisi', aciklama: 'Görev türü Çalışan olmayan personeli (aylıksız izin, yarı zamanlı, geçici/kurum görevlendirme) başlangıç/bitiş bilgisiyle listeler; müdürlük ve tür filtresi, Excel destekli.', renk: 'border-amber-200 bg-amber-50 text-amber-900', olusturulma_tarihi: '2026-04-22', kapsam_tipi: 'yok' },
]

export const RAPOR_KOD_BY_SLUG = Object.fromEntries(RAPOR_TANIMLARI.map(r => [r.slug, r.kod])) as Record<string, string>

export function raporTanimByKod(kod: string): RaporTanim | undefined {
  return RAPOR_TANIMLARI.find(r => r.kod === kod)
}
