-- Yerel Bilgi > Tanımlar: Araç Sahiplik Durumu
-- Yerel Bilgi > İşlemler: Araç kayıtları

CREATE TABLE IF NOT EXISTS public.yerel_bilgi_arac_sahiplik_durum (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sira_no integer,
  tanim_adi text NOT NULL,
  aktif boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.yerel_bilgi_arac (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sahiplik_durum_id bigint NOT NULL
    CONSTRAINT yerel_bilgi_arac_sahiplik_durum_id_fkey REFERENCES public.yerel_bilgi_arac_sahiplik_durum (id) ON DELETE RESTRICT,
  arac_durum_id bigint NOT NULL
    CONSTRAINT yerel_bilgi_arac_arac_durum_id_fkey REFERENCES public.yerel_bilgi_arac_durum (id) ON DELETE RESTRICT,
  arac_turu_id bigint NOT NULL
    CONSTRAINT yerel_bilgi_arac_arac_turu_id_fkey REFERENCES public.yerel_bilgi_arac_turu (id) ON DELETE RESTRICT,
  arac_alt_tur_id bigint NOT NULL
    CONSTRAINT yerel_bilgi_arac_arac_alt_tur_id_fkey REFERENCES public.yerel_bilgi_arac_alt_tur (id) ON DELETE RESTRICT,
  plaka_no text,
  sasi_no text,
  mudurluk_id bigint NOT NULL
    CONSTRAINT yerel_bilgi_arac_mudurluk_id_fkey REFERENCES public.tanim_mudurluk (id) ON DELETE RESTRICT,
  created_by uuid CONSTRAINT yerel_bilgi_arac_created_by_fkey REFERENCES auth.users (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.yerel_bilgi_arac_sahiplik_durum IS 'Yerel Bilgi > Tanımlar > Araç Sahiplik Durumu';
COMMENT ON TABLE public.yerel_bilgi_arac IS 'Yerel Bilgi > İşlemler > Araç bilgisi kayıtları';

CREATE INDEX IF NOT EXISTS idx_yerel_bilgi_arac_mudurluk ON public.yerel_bilgi_arac (mudurluk_id);
CREATE INDEX IF NOT EXISTS idx_yerel_bilgi_arac_created_at ON public.yerel_bilgi_arac (created_at DESC);

-- Alt türün seçilen türe ait olduğunu doğrula
CREATE OR REPLACE FUNCTION public.yerel_bilgi_arac_alt_tur_turu_kontrol()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  tur_id bigint;
BEGIN
  SELECT arac_turu_id INTO tur_id FROM public.yerel_bilgi_arac_alt_tur WHERE id = NEW.arac_alt_tur_id;
  IF tur_id IS DISTINCT FROM NEW.arac_turu_id THEN
    RAISE EXCEPTION 'Araç alt türü, seçilen araç türüne ait değil.';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_yerel_bilgi_arac_alt_tur_turu ON public.yerel_bilgi_arac;
CREATE TRIGGER tr_yerel_bilgi_arac_alt_tur_turu
  BEFORE INSERT OR UPDATE OF arac_turu_id, arac_alt_tur_id ON public.yerel_bilgi_arac
  FOR EACH ROW
  EXECUTE PROCEDURE public.yerel_bilgi_arac_alt_tur_turu_kontrol();

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['yerel_bilgi_arac_sahiplik_durum', 'yerel_bilgi_arac']
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS "authenticated_full_access" ON public.%I', t);
    EXECUTE format(
      'CREATE POLICY "authenticated_full_access" ON public.%I FOR ALL USING (auth.role() = ''authenticated'')',
      t
    );
  END LOOP;
END $$;
