-- Bildirim · Aylık İzin İşlemleri

create table if not exists public.aylik_izin_bildirimleri (
  id bigint generated by default as identity primary key,
  sicil_no text not null,
  ad_soyad text not null,
  tckn text null,
  unvan text not null,
  mudurluk text not null,
  baslangic_tarihi date not null,
  bitis_tarihi date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  created_by_email text null
);

comment on table public.aylik_izin_bildirimleri is
  '657 SK m.108(e) aylık izin talep dilekçesi kayıtları.';

create index if not exists idx_aylik_izin_sicil on public.aylik_izin_bildirimleri (sicil_no);
create index if not exists idx_aylik_izin_created on public.aylik_izin_bildirimleri (created_at desc);

alter table public.aylik_izin_bildirimleri enable row level security;

do $$
declare
  tbl text := 'aylik_izin_bildirimleri';
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = tbl and policyname = tbl || '_select'
  ) then
    execute format(
      'create policy %I on public.%I for select to authenticated using (
        public.is_admin_like(auth.uid())
        or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
        or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
      )',
      tbl || '_select', tbl
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = tbl and policyname = tbl || '_insert'
  ) then
    execute format(
      'create policy %I on public.%I for insert to authenticated with check (
        public.is_admin_like(auth.uid())
        or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
        or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
      )',
      tbl || '_insert', tbl
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = tbl and policyname = tbl || '_delete'
  ) then
    execute format(
      'create policy %I on public.%I for delete to authenticated using (
        public.is_admin_like(auth.uid())
        or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      )',
      tbl || '_delete', tbl
    );
  end if;
end
$$;
