-- SMS log: planlanan gönderim takibi ve olay geçmişi

alter table public.iletisim_sms_log
  add column if not exists baglam text null,
  add column if not exists planlanan_gonderim_at timestamptz null,
  add column if not exists gonderim_kontrol_at timestamptz null;

comment on column public.iletisim_sms_log.baglam is
  'Gönderim bağlamı: tekil, dogum_gunu, hosgeldin_bebek, grup vb.';
comment on column public.iletisim_sms_log.planlanan_gonderim_at is
  'Sağlayıcıya iletilen planlı gönderim zamanı (doğum günü vb.).';
comment on column public.iletisim_sms_log.gonderim_kontrol_at is
  'Son sağlayıcı durum sorgusu zamanı.';

create index if not exists idx_iletisim_sms_log_planlanan
  on public.iletisim_sms_log (planlanan_gonderim_at)
  where durum = 'planlandi';

create table if not exists public.iletisim_sms_log_olay (
  id bigint generated by default as identity primary key,
  log_id bigint not null references public.iletisim_sms_log (id) on delete cascade,
  olay_tipi text not null,
  aciklama text not null,
  saglayici_durum text null,
  created_at timestamptz not null default now()
);

comment on table public.iletisim_sms_log_olay is
  'SMS gönderim kaydı olay geçmişi (planlandı, iletildi, başarısız, kontrol vb.).';

create index if not exists idx_iletisim_sms_log_olay_log
  on public.iletisim_sms_log_olay (log_id, created_at desc);

alter table public.iletisim_sms_log_olay enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'iletisim_sms_log'
      and policyname = 'iletisim_sms_log_admin_update'
  ) then
    create policy iletisim_sms_log_admin_update
    on public.iletisim_sms_log
    for update
    to authenticated
    using (public.is_admin_like(auth.uid()))
    with check (public.is_admin_like(auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'iletisim_sms_log_olay'
      and policyname = 'iletisim_sms_log_olay_admin_select'
  ) then
    create policy iletisim_sms_log_olay_admin_select
    on public.iletisim_sms_log_olay
    for select
    to authenticated
    using (public.is_admin_like(auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'iletisim_sms_log_olay'
      and policyname = 'iletisim_sms_log_olay_admin_insert'
  ) then
    create policy iletisim_sms_log_olay_admin_insert
    on public.iletisim_sms_log_olay
    for insert
    to authenticated
    with check (public.is_admin_like(auth.uid()));
  end if;
end
$$;
