-- İletişim Yönetimi · SMS entegrasyonu (mesajpaketi.com)
-- Ayar tablosu (tekil kayıt id=1) ve gönderim log tablosu.

create table if not exists public.iletisim_sms_ayar (
  id smallint primary key default 1,
  saglayici text not null default 'mesajpaketi',
  api_base_url text not null default 'https://www.mesajpaketi.com',
  kullanici_adi text null,
  sifre text null,
  originator text null,
  turkce_karakter boolean not null default true,
  aktif boolean not null default false,
  updated_at timestamptz not null default now(),
  constraint iletisim_sms_ayar_tekil check (id = 1)
);

comment on table public.iletisim_sms_ayar is
  'SMS sağlayıcı (mesajpaketi.com) API ayarları; tekil kayıt (id=1). Yalnızca admin erişebilir.';

insert into public.iletisim_sms_ayar (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.iletisim_sms_log (
  id bigint generated by default as identity primary key,
  actor_id uuid null references auth.users (id) on update cascade on delete set null,
  actor_email text null,
  alici_sicil text null,
  alici_ad text null,
  telefon text not null,
  mesaj text not null,
  originator text null,
  durum text not null default 'gonderildi',
  saglayici_mesaj_id text null,
  hata_kodu text null,
  hata_mesaji text null,
  created_at timestamptz not null default now()
);

comment on table public.iletisim_sms_log is
  'Gönderilen SMS kayıtları (kim, kime, metin, sağlayıcı yanıtı/durum).';

create index if not exists idx_iletisim_sms_log_created_at
  on public.iletisim_sms_log (created_at desc);

create index if not exists idx_iletisim_sms_log_alici_sicil
  on public.iletisim_sms_log (alici_sicil);

-- RLS: yalnızca admin
alter table public.iletisim_sms_ayar enable row level security;
alter table public.iletisim_sms_log enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'iletisim_sms_ayar'
      and policyname = 'iletisim_sms_ayar_admin_all'
  ) then
    create policy iletisim_sms_ayar_admin_all
    on public.iletisim_sms_ayar
    for all
    to authenticated
    using (public.is_admin_like(auth.uid()))
    with check (public.is_admin_like(auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'iletisim_sms_log'
      and policyname = 'iletisim_sms_log_admin_select'
  ) then
    create policy iletisim_sms_log_admin_select
    on public.iletisim_sms_log
    for select
    to authenticated
    using (public.is_admin_like(auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'iletisim_sms_log'
      and policyname = 'iletisim_sms_log_admin_insert'
  ) then
    create policy iletisim_sms_log_admin_insert
    on public.iletisim_sms_log
    for insert
    to authenticated
    with check (public.is_admin_like(auth.uid()) and (actor_id is null or actor_id = auth.uid()));
  end if;
end
$$;
