-- Tanımlar · Organizasyon yapısı (kurumun birim hiyerarşisi)

-- Organizasyon başlığı (ad + aktif/pasif)
create table if not exists public.tanim_organizasyon (
  id bigint generated by default as identity primary key,
  organizasyon_adi text not null,
  aktif boolean not null default true,
  created_at timestamptz not null default now()
);

comment on table public.tanim_organizasyon is 'Kurum organizasyon yapısı başlığı.';

-- Organizasyona eklenen birimler (müdürlük) ve bağlı olduğu üst birim
create table if not exists public.tanim_organizasyon_birim (
  id bigint generated by default as identity primary key,
  organizasyon_id bigint not null references public.tanim_organizasyon (id) on delete cascade,
  mudurluk_id bigint not null references public.tanim_mudurluk (id) on delete cascade,
  ust_birim_id bigint null references public.tanim_organizasyon_birim (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (organizasyon_id, mudurluk_id)
);

comment on table public.tanim_organizasyon_birim is 'Organizasyona bağlı birimler ve üst birim ilişkisi.';
comment on column public.tanim_organizasyon_birim.ust_birim_id is 'Bağlı olduğu üst birim (boş ise en üst birim).';

create index if not exists idx_tanim_organizasyon_birim_org on public.tanim_organizasyon_birim (organizasyon_id);
create index if not exists idx_tanim_organizasyon_birim_ust on public.tanim_organizasyon_birim (ust_birim_id);

-- RLS: diğer tanım tablolarıyla aynı (okuma authenticated; yazma uygulama katmanında requireTanimlarYazma ile sınırlı)
alter table public.tanim_organizasyon enable row level security;
drop policy if exists "authenticated_full_access" on public.tanim_organizasyon;
create policy "authenticated_full_access" on public.tanim_organizasyon
  for all using (auth.role() = 'authenticated');

alter table public.tanim_organizasyon_birim enable row level security;
drop policy if exists "authenticated_full_access" on public.tanim_organizasyon_birim;
create policy "authenticated_full_access" on public.tanim_organizasyon_birim
  for all using (auth.role() = 'authenticated');
