-- Bildirim · Okula Uyum İzni

create table if not exists public.okula_uyum_izni_bildirimleri (
  id bigint generated by default as identity primary key,
  sicil_no text not null,
  ad_soyad text not null,
  tckn text null,
  unvan text not null,
  mudurluk text not null,
  ogrenci_ad_soyad text not null,
  baslayacagi_sinif text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  created_by_email text null,
  constraint okula_uyum_izni_sinif_chk check (baslayacagi_sinif in ('1. Sınıf', '5. Sınıf'))
);

comment on table public.okula_uyum_izni_bildirimleri is
  'Okula uyum haftası üç saatlik idari izin talep dilekçesi kayıtları.';

create index if not exists idx_okula_uyum_izni_sicil on public.okula_uyum_izni_bildirimleri (sicil_no);
create index if not exists idx_okula_uyum_izni_created on public.okula_uyum_izni_bildirimleri (created_at desc);

alter table public.okula_uyum_izni_bildirimleri enable row level security;

do $$
declare
  tbl text := 'okula_uyum_izni_bildirimleri';
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = tbl and policyname = tbl || '_select'
  ) then
    execute format(
      'create policy %I on public.%I for select to authenticated using (
        public.is_admin_like(auth.uid())
        or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
        or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
      )',
      tbl || '_select', tbl
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = tbl and policyname = tbl || '_insert'
  ) then
    execute format(
      'create policy %I on public.%I for insert to authenticated with check (
        public.is_admin_like(auth.uid())
        or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
        or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
      )',
      tbl || '_insert', tbl
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = tbl and policyname = tbl || '_delete'
  ) then
    execute format(
      'create policy %I on public.%I for delete to authenticated using (
        public.is_admin_like(auth.uid())
        or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      )',
      tbl || '_delete', tbl
    );
  end if;
end
$$;
