-- Araç kaydı aktif/pasif + bütçe tahmin / gider işlem tabloları

ALTER TABLE public.yerel_bilgi_arac ADD COLUMN IF NOT EXISTS aktif boolean NOT NULL DEFAULT true;

CREATE SEQUENCE IF NOT EXISTS public.yerel_bilgi_butce_tahmin_islem_sira_seq;
CREATE SEQUENCE IF NOT EXISTS public.yerel_bilgi_butce_gider_islem_sira_seq;

CREATE TABLE IF NOT EXISTS public.yerel_bilgi_butce_tahmin_islem (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sira_no bigint NOT NULL DEFAULT nextval('public.yerel_bilgi_butce_tahmin_islem_sira_seq'),
  mudurluk_id bigint NOT NULL
    CONSTRAINT yerel_bilgi_butce_tahmin_islem_mudurluk_id_fkey REFERENCES public.tanim_mudurluk (id) ON DELETE RESTRICT,
  butce_gider_kalem_id bigint NOT NULL
    CONSTRAINT yerel_bilgi_butce_tahmin_islem_kalem_fkey REFERENCES public.yerel_bilgi_butce_gider (id) ON DELETE RESTRICT,
  tutar numeric(18, 2),
  aktif boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.yerel_bilgi_butce_gider_islem (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sira_no bigint NOT NULL DEFAULT nextval('public.yerel_bilgi_butce_gider_islem_sira_seq'),
  mudurluk_id bigint NOT NULL
    CONSTRAINT yerel_bilgi_butce_gider_islem_mudurluk_id_fkey REFERENCES public.tanim_mudurluk (id) ON DELETE RESTRICT,
  butce_gider_kalem_id bigint NOT NULL
    CONSTRAINT yerel_bilgi_butce_gider_islem_kalem_fkey REFERENCES public.yerel_bilgi_butce_gider (id) ON DELETE RESTRICT,
  tutar numeric(18, 2),
  aktif boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.yerel_bilgi_butce_tahmin_islem IS 'Yerel Bilgi > Bütçe tahminleri girişi (sütun yılı: cari+1)';
COMMENT ON TABLE public.yerel_bilgi_butce_gider_islem IS 'Yerel Bilgi > Bütçe gerçekleşmeleri gider girişi (sütun yılı: cari yıl)';

CREATE INDEX IF NOT EXISTS idx_ybti_sira ON public.yerel_bilgi_butce_tahmin_islem (sira_no ASC);
CREATE INDEX IF NOT EXISTS idx_ybgi_sira ON public.yerel_bilgi_butce_gider_islem (sira_no ASC);

COMMENT ON COLUMN public.yerel_bilgi_arac.aktif IS 'Kayıt durumu (liste: müdürlükten sonra)';

-- Sıra dizilerini tablodaki MAX ile eşitle (boş tabloda setval(...,0) geçersiz; 1,false kullan)
DO $$
DECLARE
  mx bigint;
BEGIN
  SELECT MAX(sira_no) INTO mx FROM public.yerel_bilgi_butce_tahmin_islem;
  IF mx IS NULL THEN
    PERFORM setval('public.yerel_bilgi_butce_tahmin_islem_sira_seq', 1, false);
  ELSE
    PERFORM setval('public.yerel_bilgi_butce_tahmin_islem_sira_seq', mx, true);
  END IF;

  SELECT MAX(sira_no) INTO mx FROM public.yerel_bilgi_butce_gider_islem;
  IF mx IS NULL THEN
    PERFORM setval('public.yerel_bilgi_butce_gider_islem_sira_seq', 1, false);
  ELSE
    PERFORM setval('public.yerel_bilgi_butce_gider_islem_sira_seq', mx, true);
  END IF;
END $$;

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['yerel_bilgi_butce_tahmin_islem', 'yerel_bilgi_butce_gider_islem']
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS "authenticated_full_access" ON public.%I', t);
    EXECUTE format(
      'CREATE POLICY "authenticated_full_access" ON public.%I FOR ALL USING (auth.role() = ''authenticated'')',
      t
    );
  END LOOP;
END $$;
