-- İletişim · SMS widget genişlemesi: ek originator alanları ve mesaj şablonları

alter table public.iletisim_sms_ayar
  add column if not exists originator2 text,
  add column if not exists originator3 text;

create table if not exists public.iletisim_sms_sablon (
  id bigint generated by default as identity primary key,
  tur text not null default 'genel',
  baslik text not null,
  metin text not null,
  aktif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint iletisim_sms_sablon_tur_check
    check (tur in ('dogum_gunu', 'hosgeldin_bebek', 'evlilik', 'genel'))
);

comment on table public.iletisim_sms_sablon is
  'SMS mesaj şablonları. tur: dogum_gunu | hosgeldin_bebek | evlilik | genel. metin içinde {ad_soyad}, {ad}, {cocuk_adi} yer tutucuları kullanılabilir.';

create index if not exists idx_iletisim_sms_sablon_tur
  on public.iletisim_sms_sablon (tur, aktif);

alter table public.iletisim_sms_sablon enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'iletisim_sms_sablon'
      and policyname = 'iletisim_sms_sablon_admin_all'
  ) then
    create policy iletisim_sms_sablon_admin_all
    on public.iletisim_sms_sablon
    for all
    to authenticated
    using (public.is_admin_like(auth.uid()))
    with check (public.is_admin_like(auth.uid()));
  end if;
end
$$;
