-- Yerel Bilgi Yönetimi > Tanımlar

CREATE TABLE IF NOT EXISTS public.yerel_bilgi_arac_durum (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sira_no integer,
  tanim_adi text NOT NULL,
  aktif boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.yerel_bilgi_arac_turu (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sira_no integer,
  tanim_adi text NOT NULL,
  aktif boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.yerel_bilgi_arac_alt_tur (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  arac_turu_id bigint NOT NULL REFERENCES public.yerel_bilgi_arac_turu (id) ON DELETE CASCADE,
  sira_no integer,
  tanim_adi text NOT NULL,
  aktif boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_yerel_bilgi_arac_alt_tur_turu ON public.yerel_bilgi_arac_alt_tur (arac_turu_id);

CREATE TABLE IF NOT EXISTS public.yerel_bilgi_butce_gider (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sira_no integer,
  tanim_adi text NOT NULL,
  aktif boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.yerel_bilgi_butce_gelir (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sira_no integer,
  tanim_adi text NOT NULL,
  aktif boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.yerel_bilgi_arac_durum IS 'Yerel Bilgi > Tanımlar > Araç Durum';
COMMENT ON TABLE public.yerel_bilgi_arac_turu IS 'Yerel Bilgi > Tanımlar > Araç Türü (üst)';
COMMENT ON TABLE public.yerel_bilgi_arac_alt_tur IS 'Yerel Bilgi > Tanımlar > Araç Alt Türü';
COMMENT ON TABLE public.yerel_bilgi_butce_gider IS 'Yerel Bilgi > Tanımlar > Bütçe Gider';
COMMENT ON TABLE public.yerel_bilgi_butce_gelir IS 'Yerel Bilgi > Tanımlar > Bütçe Gelir';

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'yerel_bilgi_arac_durum',
    'yerel_bilgi_arac_turu',
    'yerel_bilgi_arac_alt_tur',
    'yerel_bilgi_butce_gider',
    'yerel_bilgi_butce_gelir'
  ]
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS "authenticated_full_access" ON public.%I', t);
    EXECUTE format(
      'CREATE POLICY "authenticated_full_access" ON public.%I FOR ALL USING (auth.role() = ''authenticated'')',
      t
    );
  END LOOP;
END $$;
