-- Sendika tanımları ve personel sendika üyelik kayıtları

create table if not exists public.tanim_sendika (
  id bigint generated by default as identity primary key,
  statu text not null check (statu in ('Memur', 'İşçi')),
  kisa_ad text not null,
  uzun_ad text not null,
  aktif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.tanim_sendika is 'Sendika tanımları (kısa/uzun ad, memur veya işçi sendikası).';
comment on column public.tanim_sendika.statu is 'Memur veya İşçi sendikası kategorisi';

create index if not exists idx_tanim_sendika_statu_kisa on public.tanim_sendika (statu, kisa_ad);
create index if not exists idx_tanim_sendika_aktif on public.tanim_sendika (aktif);

alter table public.tanim_sendika enable row level security;

create table if not exists public.personel_sendika (
  id bigint generated by default as identity primary key,
  sicil_no text not null references public.calisan (sicil_no) on delete cascade,
  sendika_id bigint not null references public.tanim_sendika (id) on delete restrict,
  baslangic_tarihi date not null default (current_date),
  bitis_tarihi date null,
  aktif boolean not null default true,
  kayit_zamani timestamptz not null default now()
);

comment on table public.personel_sendika is 'Personel sendika üyelik geçmişi; yeni kayıt önceki aktif kaydı pasifleştirir.';

create index if not exists idx_personel_sendika_sicil on public.personel_sendika (sicil_no);
create index if not exists idx_personel_sendika_aktif on public.personel_sendika (sicil_no, aktif) where aktif = true;
create index if not exists idx_personel_sendika_sendika on public.personel_sendika (sendika_id);
create index if not exists idx_personel_sendika_baslangic on public.personel_sendika (baslangic_tarihi desc);

alter table public.personel_sendika enable row level security;

do $$
declare
  tbl text;
begin
  foreach tbl in array array['tanim_sendika', 'personel_sendika']
  loop
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl and policyname = tbl || '_select'
    ) then
      execute format(
        'create policy %I on public.%I for select to authenticated using (
          public.is_admin_like(auth.uid())
          or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
        )',
        tbl || '_select',
        tbl
      );
    end if;
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl and policyname = tbl || '_all'
    ) then
      execute format(
        'create policy %I on public.%I for all to authenticated using (
          public.is_admin_like(auth.uid())
        ) with check (
          public.is_admin_like(auth.uid())
        )',
        tbl || '_all',
        tbl
      );
    end if;
  end loop;
end $$;
