create table if not exists public.performans_programi_alt_program (
  id bigint generated by default as identity primary key,
  program_id bigint not null references public.performans_programi_program(id) on delete cascade,
  sira_no integer null check (sira_no > 0),
  alt_program_adi text not null,
  aktif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.performans_programi_faaliyet (
  id bigint generated by default as identity primary key,
  alt_program_id bigint not null references public.performans_programi_alt_program(id) on delete cascade,
  sira_no integer null check (sira_no > 0),
  faaliyet_adi text not null,
  aktif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.performans_programi_faaliyet_amac (
  id bigint generated by default as identity primary key,
  faaliyet_id bigint not null references public.performans_programi_faaliyet(id) on delete cascade,
  amac_id bigint not null references public.stratejik_plan_amac(id) on delete restrict,
  aktif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (faaliyet_id, amac_id)
);

create or replace function public.set_updated_at_pp_hiyerarsi()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_pp_alt_program_updated_at on public.performans_programi_alt_program;
create trigger trg_pp_alt_program_updated_at
before update on public.performans_programi_alt_program
for each row execute function public.set_updated_at_pp_hiyerarsi();

drop trigger if exists trg_pp_faaliyet_updated_at on public.performans_programi_faaliyet;
create trigger trg_pp_faaliyet_updated_at
before update on public.performans_programi_faaliyet
for each row execute function public.set_updated_at_pp_hiyerarsi();

drop trigger if exists trg_pp_faaliyet_amac_updated_at on public.performans_programi_faaliyet_amac;
create trigger trg_pp_faaliyet_amac_updated_at
before update on public.performans_programi_faaliyet_amac
for each row execute function public.set_updated_at_pp_hiyerarsi();

alter table public.performans_programi_alt_program enable row level security;
alter table public.performans_programi_faaliyet enable row level security;
alter table public.performans_programi_faaliyet_amac enable row level security;

drop policy if exists "pp_alt_program_select_auth" on public.performans_programi_alt_program;
create policy "pp_alt_program_select_auth" on public.performans_programi_alt_program for select to authenticated using (true);
drop policy if exists "pp_alt_program_insert_auth" on public.performans_programi_alt_program;
create policy "pp_alt_program_insert_auth" on public.performans_programi_alt_program for insert to authenticated with check (true);
drop policy if exists "pp_alt_program_update_auth" on public.performans_programi_alt_program;
create policy "pp_alt_program_update_auth" on public.performans_programi_alt_program for update to authenticated using (true) with check (true);
drop policy if exists "pp_alt_program_delete_auth" on public.performans_programi_alt_program;
create policy "pp_alt_program_delete_auth" on public.performans_programi_alt_program for delete to authenticated using (true);

drop policy if exists "pp_faaliyet_select_auth" on public.performans_programi_faaliyet;
create policy "pp_faaliyet_select_auth" on public.performans_programi_faaliyet for select to authenticated using (true);
drop policy if exists "pp_faaliyet_insert_auth" on public.performans_programi_faaliyet;
create policy "pp_faaliyet_insert_auth" on public.performans_programi_faaliyet for insert to authenticated with check (true);
drop policy if exists "pp_faaliyet_update_auth" on public.performans_programi_faaliyet;
create policy "pp_faaliyet_update_auth" on public.performans_programi_faaliyet for update to authenticated using (true) with check (true);
drop policy if exists "pp_faaliyet_delete_auth" on public.performans_programi_faaliyet;
create policy "pp_faaliyet_delete_auth" on public.performans_programi_faaliyet for delete to authenticated using (true);

drop policy if exists "pp_faaliyet_amac_select_auth" on public.performans_programi_faaliyet_amac;
create policy "pp_faaliyet_amac_select_auth" on public.performans_programi_faaliyet_amac for select to authenticated using (true);
drop policy if exists "pp_faaliyet_amac_insert_auth" on public.performans_programi_faaliyet_amac;
create policy "pp_faaliyet_amac_insert_auth" on public.performans_programi_faaliyet_amac for insert to authenticated with check (true);
drop policy if exists "pp_faaliyet_amac_update_auth" on public.performans_programi_faaliyet_amac;
create policy "pp_faaliyet_amac_update_auth" on public.performans_programi_faaliyet_amac for update to authenticated using (true) with check (true);
drop policy if exists "pp_faaliyet_amac_delete_auth" on public.performans_programi_faaliyet_amac;
create policy "pp_faaliyet_amac_delete_auth" on public.performans_programi_faaliyet_amac for delete to authenticated using (true);
