-- Terfi dönemleri (Arazi Puantajı dönem yapısı ile uyumlu)

CREATE TABLE IF NOT EXISTS public.terfi_donem (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  yil integer NOT NULL,
  sira_no text,
  donem_adi text,
  baslangic_tarihi date NOT NULL,
  bitis_tarihi date NOT NULL,
  durum text NOT NULL DEFAULT 'Açık' CHECK (durum IN ('Açık', 'Kapalı')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_terfi_donem_yil ON public.terfi_donem (yil);
CREATE INDEX IF NOT EXISTS idx_terfi_donem_baslangic ON public.terfi_donem (baslangic_tarihi);

COMMENT ON TABLE public.terfi_donem IS 'Terfi işlemleri için dönem; terfi tarih filtresi bir önceki ay penceresi ile hesaplanır (TERFI_ETTIR).';
