-- Kesintiler · Aylıktan kesme bordrosu kayıtları

create table if not exists public.ayliktan_kesme_bordrolari (
  id bigint generated by default as identity primary key,
  sicil_no text not null,
  ad_soyad text not null,
  tckn text null,
  unvan text not null default '',
  mudurluk text not null default '',
  payda integer not null,
  toplam numeric not null,
  yarim_zamanli boolean not null default false,
  bordro jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  created_by_email text null,
  constraint ayliktan_kesme_payda_chk check (
    payda in (30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 4, 2)
  )
);

comment on table public.ayliktan_kesme_bordrolari is
  'Aylıktan kesme bordrosu. Tutarlar oluşturulduğu andaki asıl terfi ve kazanç tanımından hesaplanır.';

create index if not exists idx_ayliktan_kesme_sicil on public.ayliktan_kesme_bordrolari (sicil_no);
create index if not exists idx_ayliktan_kesme_created on public.ayliktan_kesme_bordrolari (created_at desc);

alter table public.ayliktan_kesme_bordrolari enable row level security;

do $$
declare
  tbl text := 'ayliktan_kesme_bordrolari';
  ok text := '(
        public.is_admin_like(auth.uid())
        or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
        or exists (
          select 1 from public.app_profiles ap
          where ap.id = auth.uid()
            and coalesce(ap.menu_izinleri->>''kesintiler'', '''') in (''true'', ''t'')
        )
      )';
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = tbl and policyname = tbl || '_select'
  ) then
    execute format(
      'create policy %I on public.%I for select to authenticated using %s',
      tbl || '_select', tbl, ok
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = tbl and policyname = tbl || '_insert'
  ) then
    execute format(
      'create policy %I on public.%I for insert to authenticated with check %s',
      tbl || '_insert', tbl, ok
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = tbl and policyname = tbl || '_update'
  ) then
    execute format(
      'create policy %I on public.%I for update to authenticated using %s with check %s',
      tbl || '_update', tbl, ok, ok
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = tbl and policyname = tbl || '_delete'
  ) then
    execute format(
      'create policy %I on public.%I for delete to authenticated using (
        public.is_admin_like(auth.uid())
        or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      )',
      tbl || '_delete', tbl
    );
  end if;
end
$$;
