-- Performans Yönetimi v1 (HR değerlendirme — Stratejik Performans Programı ile karıştırma)

-- ─── Dönem (takvim yılı) ───────────────────────────────────────────────────
create table if not exists public.performans_donem (
  id bigint generated by default as identity primary key,
  yil integer not null,
  durum text not null default 'Açık'
    check (durum in ('Açık', 'Kapalı', 'Yayınlandı')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  unique (yil)
);

comment on table public.performans_donem is
  'Memur performans değerlendirme dönemi (takvim yılı).';

-- ─── Kriter tanımları ──────────────────────────────────────────────────────
create table if not exists public.performans_kriter (
  id bigint generated by default as identity primary key,
  kod integer not null,
  baslik text not null,
  aciklama text null,
  grup text not null
    check (grup in ('ortak', 'memur', 'sef', 'yonetici')),
  sira integer not null default 0,
  aktif boolean not null default true,
  unique (kod)
);

comment on table public.performans_kriter is
  'Yetkinlik bazlı performans kriterleri (ortak + role özel).';

-- ─── SMS şablonu (2. amire bildirim) ───────────────────────────────────────
create table if not exists public.performans_sms_ayar (
  id integer primary key default 1 check (id = 1),
  metin text not null default
    'Sayın {ad_soyad}, {yil} yılı performans değerlendirmelerinde 1. amir turu tamamlanmıştır. İncelemenizi bekleyen kayıtlar bulunmaktadır.',
  updated_at timestamptz not null default now()
);

insert into public.performans_sms_ayar (id) values (1)
on conflict (id) do nothing;

-- ─── Personel değerlendirme kaydı ──────────────────────────────────────────
create table if not exists public.performans_degerlendirme (
  id bigint generated by default as identity primary key,
  donem_id bigint not null references public.performans_donem(id) on delete cascade,
  sicil_no text not null,
  form_tipi text not null
    check (form_tipi in ('memur', 'sef', 'yonetici', 'baskan')),
  durum text not null default 'beklemede_1'
    check (durum in (
      'beklemede_1',
      'amir1_gonderildi',
      'iade',
      'amir2_onay',
      'tamamlandi'
    )),
  amir1_sicil text null,
  amir2_sicil text null,
  tek_amir boolean not null default false,
  puan_amir1 integer null,
  puan_amir2 integer null,
  ortalama integer null,
  iade_notu text null,
  amir1_tamam_at timestamptz null,
  amir2_onay_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (donem_id, sicil_no)
);

create index if not exists idx_perf_deg_donem on public.performans_degerlendirme (donem_id);
create index if not exists idx_perf_deg_amir1 on public.performans_degerlendirme (amir1_sicil);
create index if not exists idx_perf_deg_amir2 on public.performans_degerlendirme (amir2_sicil);
create index if not exists idx_perf_deg_sicil on public.performans_degerlendirme (sicil_no);

-- ─── Kriter puanları (1-5) ─────────────────────────────────────────────────
create table if not exists public.performans_puan (
  id bigint generated by default as identity primary key,
  degerlendirme_id bigint not null
    references public.performans_degerlendirme(id) on delete cascade,
  kriter_id bigint not null references public.performans_kriter(id),
  puan_amir1 smallint null check (puan_amir1 is null or (puan_amir1 between 1 and 5)),
  puan_amir2 smallint null check (puan_amir2 is null or (puan_amir2 between 1 and 5)),
  unique (degerlendirme_id, kriter_id)
);

create index if not exists idx_perf_puan_deg on public.performans_puan (degerlendirme_id);

-- ─── Seed: Ek-5 kriterleri ─────────────────────────────────────────────────
insert into public.performans_kriter (kod, baslik, aciklama, grup, sira) values
  (1,  'İş Bilgisi', 'Yaptığı işe ilişkin teorik ve pratik bilgi düzeyi', 'ortak', 1),
  (2,  'Verimlilik', 'Görevini istenilen zamanda ve miktarda en uygun maliyetle yapabilme becerisi', 'ortak', 2),
  (3,  'İş Kalitesi', 'İşini standartlara uygun olarak yapabilme becerisi', 'ortak', 3),
  (4,  'Sorumluluk', 'Görev sorumluluğuyla araç ve gereçleri doğru kullanma ve sonuçları üstlenme', 'ortak', 4),
  (5,  'Problem çözme ve üretkenlik', 'Karşılaştığı problemleri hızlı ve doğru biçimde çözme, fikir geliştirme, araştırma, farklı düşünceler ortaya koyma', 'ortak', 5),
  (6,  'İnsan İlişkileri', 'Üstleri, astları, çalışma arkadaşları ve çevresi ile uyumlu ilişkiler ve sağlıklı iletişim kurma', 'ortak', 6),
  (7,  'Organizasyon Becerisi', 'Verilen görevi organize edebilme ve sonuçları takip edebilme becerisi', 'ortak', 7),
  (8,  'Öğrenmeye yatkın olma', 'Hizmetiçi eğitimlerde ve görev aldığı çalışmalarda başarılı performans gösterebilme', 'ortak', 8),
  (9,  'Girişimcilik ve yeniliklere yatkın olma', 'Güncel olayları takip edebilme, yönetime işlerin işleyişi ile ilgili yeni öneriler sunma', 'ortak', 9),
  (10, 'Takım Çalışması', 'Takım üyeleri ile işbirliği ve dayanışma içinde çalışma, bilgiyi paylaşma', 'ortak', 10),
  (11, 'Vatandaş ve çalışan odaklılık', 'Görevi diğer birim çalışanlarının ve vatandaşların arzu ve beklentileri doğrultusunda yerine getirme', 'ortak', 11),
  (12, 'Karar alma', 'Kendisini ilgilendiren konularda karar alabilme, inisiyatif kullanabilme', 'ortak', 12),
  (13, 'Programlı Çalışma', 'Çalışmaları önem ve aciliyetine göre sıraya koyarak bitirebilme', 'ortak', 13),
  (14, 'İşe Bağlılığı', 'İşi benimseyerek yapabilme, işe ve kuruma bağlılık derecesi', 'ortak', 14),
  (15, 'Esneklik', 'Yöneticisinin bilgi ve izni doğrultusunda kendisine verilen diğer görevleri yerine getirebilme', 'ortak', 15),
  (16, 'Temsil Yeteneği', 'Dış görünüş, tavır ve davranışları ile temsil yeteneği', 'memur', 16),
  (17, 'İletişim Becerisi', 'Yazılı ve sözlü iletişim ile birlikte beden dilini kullanabilme', 'memur', 17),
  (18, 'Çalışma masası ve mekânı temiz/tertipli tutma', 'İşlerini yaparken çevresini düzenli ve temiz tutma', 'memur', 18),
  (19, 'Araç-gereç koruma ve tasarruf', 'Kullandığı araç ve gereci koruma ve tasarruf yapabilme', 'memur', 19),
  (20, 'Verilen görevleri yerine getirme', 'Kendisine verilen görevle ilgili beklentileri karşılayabilme', 'memur', 20),
  (21, 'Temsil Yeteneği', 'Dış görünüş, tavır ve davranışları ile temsil yeteneği', 'sef', 21),
  (22, 'İletişim Becerisi', 'Yazılı ve sözlü iletişim ile birlikte beden dilini kullanabilme', 'sef', 22),
  (23, 'Verilen görevleri yerine getirme', 'Kendisine verilen görevle ilgili beklentileri karşılayabilme', 'sef', 23),
  (24, 'Analitik olma / problem çözme', 'Sorunlar karşısında etkili ve pratik çözümler geliştirebilme', 'sef', 24),
  (25, 'Değişen şartları kavrama ve uygulama', 'Kurum içi/dışı şartları takip edip kuruma adapte edebilme', 'sef', 25),
  (26, 'Pozitif Düşünme', 'Kendisini ve çalışanları motive etme becerisi', 'yonetici', 26),
  (27, 'Rehberlik ve Geliştirme', 'Çalışanlara örnek olma ve gelişim imkânı sunma', 'yonetici', 27),
  (28, 'Analitik olma / problem çözme', 'Sorunlar karşısında etkili ve pratik çözümler geliştirebilme', 'yonetici', 28),
  (29, 'Yetkilendirme', 'Adil iş dağılımı ve işle orantılı sorumluluk verebilme', 'yonetici', 29),
  (30, 'Değişen şartları kavrama ve uygulama', 'Kurum içi/dışı şartları takip edip kuruma adapte edebilme', 'yonetici', 30)
on conflict (kod) do nothing;

-- ─── RLS ───────────────────────────────────────────────────────────────────
alter table public.performans_donem enable row level security;
alter table public.performans_kriter enable row level security;
alter table public.performans_sms_ayar enable row level security;
alter table public.performans_degerlendirme enable row level security;
alter table public.performans_puan enable row level security;

do $$
begin
  -- donem
  if not exists (select 1 from pg_policies where tablename='performans_donem' and policyname='perf_donem_select') then
    create policy perf_donem_select on public.performans_donem for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='performans_donem' and policyname='perf_donem_write') then
    create policy perf_donem_write on public.performans_donem for all to authenticated
      using (public.is_admin_like(auth.uid()))
      with check (public.is_admin_like(auth.uid()));
  end if;

  -- kriter
  if not exists (select 1 from pg_policies where tablename='performans_kriter' and policyname='perf_kriter_select') then
    create policy perf_kriter_select on public.performans_kriter for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='performans_kriter' and policyname='perf_kriter_write') then
    create policy perf_kriter_write on public.performans_kriter for all to authenticated
      using (public.is_admin_like(auth.uid()))
      with check (public.is_admin_like(auth.uid()));
  end if;

  -- sms
  if not exists (select 1 from pg_policies where tablename='performans_sms_ayar' and policyname='perf_sms_select') then
    create policy perf_sms_select on public.performans_sms_ayar for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='performans_sms_ayar' and policyname='perf_sms_write') then
    create policy perf_sms_write on public.performans_sms_ayar for all to authenticated
      using (public.is_admin_like(auth.uid()))
      with check (public.is_admin_like(auth.uid()));
  end if;

  -- değerlendirme: admin veya ilgili siciller
  if not exists (select 1 from pg_policies where tablename='performans_degerlendirme' and policyname='perf_deg_select') then
    create policy perf_deg_select on public.performans_degerlendirme for select to authenticated
    using (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
      or amir1_sicil in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
      or amir2_sicil in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;
  if not exists (select 1 from pg_policies where tablename='performans_degerlendirme' and policyname='perf_deg_write') then
    create policy perf_deg_write on public.performans_degerlendirme for all to authenticated
    using (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or amir1_sicil in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
      or amir2_sicil in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    )
    with check (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or amir1_sicil in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
      or amir2_sicil in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;

  -- puan: değerlendirme okuyabilenler
  if not exists (select 1 from pg_policies where tablename='performans_puan' and policyname='perf_puan_select') then
    create policy perf_puan_select on public.performans_puan for select to authenticated
    using (
      exists (
        select 1 from public.performans_degerlendirme d
        where d.id = degerlendirme_id
          and (
            public.is_admin_like(auth.uid())
            or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
            or d.sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
            or d.amir1_sicil in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
            or d.amir2_sicil in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
          )
      )
    );
  end if;
  if not exists (select 1 from pg_policies where tablename='performans_puan' and policyname='perf_puan_write') then
    create policy perf_puan_write on public.performans_puan for all to authenticated
    using (
      exists (
        select 1 from public.performans_degerlendirme d
        where d.id = degerlendirme_id
          and (
            public.is_admin_like(auth.uid())
            or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
            or d.amir1_sicil in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
            or d.amir2_sicil in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
          )
      )
    )
    with check (
      exists (
        select 1 from public.performans_degerlendirme d
        where d.id = degerlendirme_id
          and (
            public.is_admin_like(auth.uid())
            or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
            or d.amir1_sicil in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
            or d.amir2_sicil in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
          )
      )
    );
  end if;
end $$;
