-- Yerel Bilgi > İşlemler > Belediye Kimlik Formu

CREATE TABLE IF NOT EXISTS public.yerel_bilgi_belediye_kimlik_formu (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sira_no bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
  form_adi text NOT NULL DEFAULT 'Belediye Kimlik Formu',
  kayit_tarihi date NOT NULL DEFAULT CURRENT_DATE,
  islem_yapan text,

  belediye_kurulus_tarihi date,
  baskan_adi text,
  baskan_soyadi text,
  baskan_cinsiyeti text,
  baskan_secime_girdigi_parti text,
  baskan_mevcut_parti text,
  baskan_donem text,
  baskan_cep_telefonu text,
  belediye_web_adresi text,
  belediye_e_posta text,
  belediye_telefon_numarasi text,
  belediye_faks_numarasi text,
  belediye_cagri_merkezi text,
  belediye_onayli_sosyal_medya_hesabi text,
  belediye_acik_adresi text,
  mahalle_sayisi integer,

  aktif boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.yerel_bilgi_belediye_kimlik_formu IS 'Yerel Bilgi > İşlemler > Belediye Kimlik Formu kayıtları';

CREATE INDEX IF NOT EXISTS idx_ybbkf_sira_no ON public.yerel_bilgi_belediye_kimlik_formu (sira_no);
CREATE INDEX IF NOT EXISTS idx_ybbkf_kayit_tarihi ON public.yerel_bilgi_belediye_kimlik_formu (kayit_tarihi DESC);

DO $$
BEGIN
  ALTER TABLE public.yerel_bilgi_belediye_kimlik_formu ENABLE ROW LEVEL SECURITY;
  DROP POLICY IF EXISTS "authenticated_full_access" ON public.yerel_bilgi_belediye_kimlik_formu;
  CREATE POLICY "authenticated_full_access" ON public.yerel_bilgi_belediye_kimlik_formu
    FOR ALL USING (auth.role() = 'authenticated');
END $$;

