-- Performans: müdürlük / tek amir tamamlanınca İK müdürüne SMS (tekrar gönderim engeli)

alter table public.performans_sms_ayar
  add column if not exists ik_tamamlanma_metin text not null default
    'Sayın {ad_soyad}, {hedef} değerlendirmesi tamamlanmıştır. Değerlendirme Formuna ait Müdürlüğünüzce yapılacak işlemleri tamamlayabilirsiniz.';

comment on column public.performans_sms_ayar.ik_tamamlanma_metin is
  'İK müdürüne tamamlanan müdürlük veya tek amir personel bildirimi. Değişkenler: {ad_soyad}, {hedef}';

create table if not exists public.performans_ik_sms_bildirim (
  id bigint generated by default as identity primary key,
  donem_id bigint not null references public.performans_donem (id) on delete cascade,
  bildirim_tipi text not null check (bildirim_tipi in ('mudurluk', 'tek_amir')),
  referans text not null,
  sms_log_id bigint null references public.iletisim_sms_log (id) on delete set null,
  created_at timestamptz not null default now(),
  unique (donem_id, bildirim_tipi, referans)
);

comment on table public.performans_ik_sms_bildirim is
  'Performans döneminde İK müdürüne gönderilen tamamlanma SMS kayıtları (müdürlük veya tek amir başına bir kez).';

create index if not exists idx_perf_ik_sms_donem on public.performans_ik_sms_bildirim (donem_id);

alter table public.performans_ik_sms_bildirim enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where tablename = 'performans_ik_sms_bildirim' and policyname = 'perf_ik_sms_select'
  ) then
    create policy perf_ik_sms_select on public.performans_ik_sms_bildirim
      for select to authenticated using (true);
  end if;
  if not exists (
    select 1 from pg_policies
    where tablename = 'performans_ik_sms_bildirim' and policyname = 'perf_ik_sms_insert'
  ) then
    create policy perf_ik_sms_insert on public.performans_ik_sms_bildirim
      for insert to authenticated with check (true);
  end if;
end $$;
