-- Bildirim · Yarı Zamanlı Çalışma İşlemleri

create table if not exists public.yari_zamanli_calisma_bildirimleri (
  id bigint generated by default as identity primary key,
  sicil_no text not null,
  ad_soyad text not null,
  tckn text null,
  unvan text not null,
  mudurluk text not null,
  cocuk_dogum_tarihi date not null,
  yari_zamanli_baslangic_tarihi date not null,
  normal_zamanli_donus_tarihi date not null,
  calisma_programi jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  created_by_email text null
);

comment on table public.yari_zamanli_calisma_bildirimleri is
  '657 SK Eki m.43 yarı zamanlı çalışma dilekçesi ve ek form kayıtları.';

create index if not exists idx_yzc_sicil on public.yari_zamanli_calisma_bildirimleri (sicil_no);
create index if not exists idx_yzc_created on public.yari_zamanli_calisma_bildirimleri (created_at desc);

alter table public.yari_zamanli_calisma_bildirimleri enable row level security;

do $$
declare
  tbl text := 'yari_zamanli_calisma_bildirimleri';
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = tbl and policyname = tbl || '_select'
  ) then
    execute format(
      'create policy %I on public.%I for select to authenticated using (
        public.is_admin_like(auth.uid())
        or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
        or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
      )',
      tbl || '_select', tbl
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = tbl and policyname = tbl || '_insert'
  ) then
    execute format(
      'create policy %I on public.%I for insert to authenticated with check (
        public.is_admin_like(auth.uid())
        or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
        or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
      )',
      tbl || '_insert', tbl
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = tbl and policyname = tbl || '_delete'
  ) then
    execute format(
      'create policy %I on public.%I for delete to authenticated using (
        public.is_admin_like(auth.uid())
        or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      )',
      tbl || '_delete', tbl
    );
  end if;
end
$$;
