alter table public.performans_programi_veri_giris
  add column if not exists birim text,
  add column if not exists onceki_yil_gerceklesme numeric,
  add column if not exists tahmin_sonraki_yil_1 numeric,
  add column if not exists tahmin_sonraki_yil_2 numeric,
  add column if not exists tahmin_sonraki_yil_3 numeric;

create table if not exists public.performans_programi_faaliyet_butce (
  id bigint generated by default as identity primary key,
  faaliyet_id bigint not null references public.stratejik_plan_faaliyet(id) on delete cascade,
  butce_kodu_id bigint not null references public.performans_programi_butce_kodu(id) on delete cascade,
  yil integer not null check (yil >= 1900 and yil <= 2500),
  mudurluk text not null,
  tutar numeric not null default 0,
  updated_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (faaliyet_id, butce_kodu_id, yil, mudurluk)
);

create index if not exists pp_faaliyet_butce_faaliyet_idx
  on public.performans_programi_faaliyet_butce (faaliyet_id, yil);

create or replace function public.set_updated_at_pp_faaliyet_butce()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_pp_faaliyet_butce_updated_at on public.performans_programi_faaliyet_butce;
create trigger trg_pp_faaliyet_butce_updated_at
before update on public.performans_programi_faaliyet_butce
for each row execute function public.set_updated_at_pp_faaliyet_butce();

alter table public.performans_programi_faaliyet_butce enable row level security;

drop policy if exists "pp_faaliyet_butce_select_auth" on public.performans_programi_faaliyet_butce;
create policy "pp_faaliyet_butce_select_auth"
  on public.performans_programi_faaliyet_butce for select to authenticated
  using (true);

drop policy if exists "pp_faaliyet_butce_insert_auth" on public.performans_programi_faaliyet_butce;
create policy "pp_faaliyet_butce_insert_auth"
  on public.performans_programi_faaliyet_butce for insert to authenticated
  with check (true);

drop policy if exists "pp_faaliyet_butce_update_auth" on public.performans_programi_faaliyet_butce;
create policy "pp_faaliyet_butce_update_auth"
  on public.performans_programi_faaliyet_butce for update to authenticated
  using (true)
  with check (true);

drop policy if exists "pp_faaliyet_butce_delete_auth" on public.performans_programi_faaliyet_butce;
create policy "pp_faaliyet_butce_delete_auth"
  on public.performans_programi_faaliyet_butce for delete to authenticated
  using (true);
