create table if not exists public.personel_audit_log (
  id bigint generated by default as identity primary key,
  sicil_no text not null references public.calisan (sicil_no) on update cascade on delete cascade,
  modul text not null,
  islem text not null,
  ozet text not null,
  actor_id uuid null references auth.users (id) on update cascade on delete set null,
  actor_email text null,
  ref_table text null,
  ref_id text null,
  onceki jsonb null,
  sonraki jsonb null,
  created_at timestamptz not null default now()
);

create index if not exists idx_personel_audit_log_sicil_created_at
  on public.personel_audit_log (sicil_no, created_at desc);

create index if not exists idx_personel_audit_log_modul
  on public.personel_audit_log (modul);

comment on table public.personel_audit_log is
  'Personel detay ekranı geçmiş sekmesi için birleşik audit timeline kaydı (Phase 1).';
