-- İSG — Tespit ve öneri kayıtları. Müdürlük adları tanim_mudurluk kökünden okunur.

create table if not exists public.isg_tespit_oneri (
  id bigint generated by default as identity primary key,
  sira_no integer not null,
  isyeri_mudurluk_id integer not null references public.tanim_mudurluk(id),
  tespit_oneri text not null,
  sorumlu_mudurluk_id integer not null references public.tanim_mudurluk(id),
  isbirligi_mudurluk_id integer null references public.tanim_mudurluk(id),
  durum text not null,
  son_tarih date not null,
  created_at timestamptz not null default now(),
  constraint isg_tespit_oneri_durum_check
    check (durum in ('Planlandı', 'Devam Ediyor', 'Kontrolde', 'Tamamlandı'))
);

comment on table public.isg_tespit_oneri is
  'İSG tespit ve öneri işlemleri. İşyeri, sorumlu ve iş birliği müdürlükleri tanim_mudurluk kaydına bağlıdır.';

create unique index if not exists isg_tespit_oneri_sira_no_key
  on public.isg_tespit_oneri (sira_no);

alter table public.isg_tespit_oneri enable row level security;

drop policy if exists isg_tespit_oneri_select on public.isg_tespit_oneri;
drop policy if exists isg_tespit_oneri_write on public.isg_tespit_oneri;

create policy isg_tespit_oneri_select
  on public.isg_tespit_oneri
  for select
  to authenticated
  using (true);

create policy isg_tespit_oneri_write
  on public.isg_tespit_oneri
  for all
  to authenticated
  using (true)
  with check (true);

grant select, insert, update, delete on public.isg_tespit_oneri to authenticated;
