-- Bildirim · Pasaport işlemleri (yeşil pasaport başvuru formu kayıtları)

create table if not exists public.pasaport_islemleri (
  id bigint generated by default as identity primary key,
  sicil_no text not null references public.calisan (sicil_no) on update cascade,
  ad_soyad text not null,
  tckn text null,
  kadro_id bigint null,
  mudurluk text null,
  derece text null,
  unvan text null,
  statu text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  created_by_email text null
);

comment on table public.pasaport_islemleri is 'Yeşil pasaport başvuru formu kayıtları (seçilen kadro anlık görüntüsü).';

create index if not exists idx_pasaport_islemleri_sicil on public.pasaport_islemleri (sicil_no);
create index if not exists idx_pasaport_islemleri_created on public.pasaport_islemleri (created_at desc);

alter table public.pasaport_islemleri enable row level security;

-- Admin tümü; profili olmayan (full) erişim; kullanıcı yalnızca kendi sicili.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'pasaport_islemleri'
      and policyname = 'pasaport_islemleri_select'
  ) then
    create policy pasaport_islemleri_select
    on public.pasaport_islemleri
    for select
    to authenticated
    using (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'pasaport_islemleri'
      and policyname = 'pasaport_islemleri_insert'
  ) then
    create policy pasaport_islemleri_insert
    on public.pasaport_islemleri
    for insert
    to authenticated
    with check (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'pasaport_islemleri'
      and policyname = 'pasaport_islemleri_update'
  ) then
    create policy pasaport_islemleri_update
    on public.pasaport_islemleri
    for update
    to authenticated
    using (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    )
    with check (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'pasaport_islemleri'
      and policyname = 'pasaport_islemleri_delete'
  ) then
    create policy pasaport_islemleri_delete
    on public.pasaport_islemleri
    for delete
    to authenticated
    using (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;
end
$$;
