-- İSG — Sağlık Taraması dönem ve personel kayıtları

create table if not exists public.isg_saglik_taramasi_donem (
  id bigint generated by default as identity primary key,
  sira_no integer not null,
  donem_adi text not null,
  baslangic_tarihi date not null,
  bitis_tarihi date not null,
  created_at timestamptz not null default now()
);

comment on table public.isg_saglik_taramasi_donem is
  'İSG sağlık taraması dönem tanımları.';

create unique index if not exists isg_saglik_taramasi_donem_sira_no_key
  on public.isg_saglik_taramasi_donem (sira_no);

create table if not exists public.isg_saglik_taramasi_kayit (
  id bigint generated by default as identity primary key,
  donem_id bigint not null references public.isg_saglik_taramasi_donem(id) on delete cascade,
  sicil_no text not null references public.calisan(sicil_no) on delete cascade,
  tarama boolean not null default false,
  muayene boolean not null default false,
  mudurluk text null,
  created_at timestamptz not null default now(),
  unique (donem_id, sicil_no)
);

comment on table public.isg_saglik_taramasi_kayit is
  'Dönem bazlı sağlık taraması / muayene işaretlemeleri.';

create index if not exists isg_saglik_taramasi_kayit_donem_idx
  on public.isg_saglik_taramasi_kayit (donem_id);
