create table if not exists public.performans_programi_butce_kodu (
  id bigint generated by default as identity primary key,
  adim_1 text not null,
  adim_2 text not null,
  adim_3 text not null,
  adim_4 text not null,
  hesap_adi text not null,
  ekonomik_kod text not null unique,
  aktif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pp_butce_kodu_ekonomik_idx
  on public.performans_programi_butce_kodu (ekonomik_kod);

create or replace function public.set_updated_at_pp_butce_kodu()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_pp_butce_kodu_updated_at on public.performans_programi_butce_kodu;
create trigger trg_pp_butce_kodu_updated_at
before update on public.performans_programi_butce_kodu
for each row execute function public.set_updated_at_pp_butce_kodu();

alter table public.performans_programi_butce_kodu enable row level security;

drop policy if exists "pp_butce_kodu_select_auth" on public.performans_programi_butce_kodu;
create policy "pp_butce_kodu_select_auth"
  on public.performans_programi_butce_kodu for select to authenticated
  using (true);

drop policy if exists "pp_butce_kodu_insert_auth" on public.performans_programi_butce_kodu;
create policy "pp_butce_kodu_insert_auth"
  on public.performans_programi_butce_kodu for insert to authenticated
  with check (true);

drop policy if exists "pp_butce_kodu_update_auth" on public.performans_programi_butce_kodu;
create policy "pp_butce_kodu_update_auth"
  on public.performans_programi_butce_kodu for update to authenticated
  using (true)
  with check (true);

drop policy if exists "pp_butce_kodu_delete_auth" on public.performans_programi_butce_kodu;
create policy "pp_butce_kodu_delete_auth"
  on public.performans_programi_butce_kodu for delete to authenticated
  using (true);
