-- Sosyal Hak IZY: dönem+sicil bazlı K (kesinti) manuel düzeltme
-- Örn. yazılım öncesi Haziran düzeltmesi (Ali Kazancı / sicil 180 → K=43)

create table if not exists public.sosyal_hak_izy_ksd_override (
  id bigint generated by default as identity primary key,
  donem_id bigint not null references public.sosyal_hak_donem (id) on delete cascade,
  sicil_no text not null,
  k_override integer not null,
  sd_override integer null,
  not_lar text null,
  created_at timestamptz not null default now(),
  constraint sosyal_hak_izy_ksd_override_donem_sicil_unique unique (donem_id, sicil_no)
);

comment on table public.sosyal_hak_izy_ksd_override is
  'Sosyal Hak IZY özetinde dönem+sicil için K (kesinti) manuel düzeltme. sd_override null ise SD = max(0, eski_K+eski_SD - k_override).';
comment on column public.sosyal_hak_izy_ksd_override.k_override is 'Zorlanan kesinti (K) günü.';
comment on column public.sosyal_hak_izy_ksd_override.sd_override is 'Opsiyonel; verilmezse bakiye korunarak SD yeniden hesaplanır.';

create index if not exists idx_sosyal_hak_izy_ksd_override_donem
  on public.sosyal_hak_izy_ksd_override (donem_id);

alter table public.sosyal_hak_izy_ksd_override enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'sosyal_hak_izy_ksd_override'
      and policyname = 'sosyal_hak_izy_ksd_override_admin_all'
  ) then
    create policy sosyal_hak_izy_ksd_override_admin_all
    on public.sosyal_hak_izy_ksd_override
    for all
    to authenticated
    using (public.is_admin_like(auth.uid()))
    with check (public.is_admin_like(auth.uid()));
  end if;
end
$$;

-- Ali Kazancı (180) — Sosyal Hak dönem #6 (Haziran) kesinti = 43
insert into public.sosyal_hak_izy_ksd_override (donem_id, sicil_no, k_override, not_lar)
select 6, '180', 43, 'Yazılım öncesi Haziran düzeltmesi — Ali Kazancı'
where exists (select 1 from public.sosyal_hak_donem where id = 6)
on conflict (donem_id, sicil_no) do update set
  k_override = excluded.k_override,
  sd_override = excluded.sd_override,
  not_lar = excluded.not_lar;
