-- İletişim · SMS grupları (kalıcı alıcı grupları)

create table if not exists public.iletisim_sms_grup (
  id bigint generated by default as identity primary key,
  ad text not null,
  aciklama text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.iletisim_sms_grup is 'SMS gönderimi için kayıtlı alıcı grupları.';

create table if not exists public.iletisim_sms_grup_uye (
  grup_id bigint not null references public.iletisim_sms_grup (id) on delete cascade,
  sicil_no text not null references public.calisan (sicil_no) on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  primary key (grup_id, sicil_no)
);

comment on table public.iletisim_sms_grup_uye is 'SMS grubu üyeleri (personel sicilleri).';

create index if not exists idx_iletisim_sms_grup_uye_grup on public.iletisim_sms_grup_uye (grup_id);

alter table public.iletisim_sms_grup enable row level security;
alter table public.iletisim_sms_grup_uye enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'iletisim_sms_grup'
      and policyname = 'iletisim_sms_grup_admin_all'
  ) then
    create policy iletisim_sms_grup_admin_all
    on public.iletisim_sms_grup
    for all
    to authenticated
    using (public.is_admin_like(auth.uid()))
    with check (public.is_admin_like(auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'iletisim_sms_grup_uye'
      and policyname = 'iletisim_sms_grup_uye_admin_all'
  ) then
    create policy iletisim_sms_grup_uye_admin_all
    on public.iletisim_sms_grup_uye
    for all
    to authenticated
    using (public.is_admin_like(auth.uid()))
    with check (public.is_admin_like(auth.uid()));
  end if;
end
$$;
