-- Bildirim · Çalışma Belgesi, BES İptal, Sendika İstifa

create table if not exists public.calisma_belgesi_bildirimleri (
  id bigint generated by default as identity primary key,
  sicil_no text not null,
  ad_soyad text not null,
  tckn text null,
  unvan text not null,
  mudurluk text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  created_by_email text null
);

comment on table public.calisma_belgesi_bildirimleri is
  'Çalışma belgesi talep dilekçesi kayıtları.';

create index if not exists idx_calisma_belgesi_sicil on public.calisma_belgesi_bildirimleri (sicil_no);
create index if not exists idx_calisma_belgesi_created on public.calisma_belgesi_bildirimleri (created_at desc);

alter table public.calisma_belgesi_bildirimleri enable row level security;

create table if not exists public.bes_iptal_bildirimleri (
  id bigint generated by default as identity primary key,
  sicil_no text not null,
  ad_soyad text not null,
  tckn text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  created_by_email text null
);

comment on table public.bes_iptal_bildirimleri is
  'BES/OKS iptal talep dilekçesi kayıtları.';

create index if not exists idx_bes_iptal_sicil on public.bes_iptal_bildirimleri (sicil_no);
create index if not exists idx_bes_iptal_created on public.bes_iptal_bildirimleri (created_at desc);

alter table public.bes_iptal_bildirimleri enable row level security;

create table if not exists public.sendika_istifa_bildirimleri (
  id bigint generated by default as identity primary key,
  sicil_no text not null,
  ad_soyad text not null,
  tckn text null,
  sendika_adi text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  created_by_email text null
);

comment on table public.sendika_istifa_bildirimleri is
  'Sendika istifa bildirimi dilekçe kayıtları.';

create index if not exists idx_sendika_istifa_sicil on public.sendika_istifa_bildirimleri (sicil_no);
create index if not exists idx_sendika_istifa_created on public.sendika_istifa_bildirimleri (created_at desc);

alter table public.sendika_istifa_bildirimleri enable row level security;

do $$
declare
  tbl text;
begin
  foreach tbl in array array[
    'calisma_belgesi_bildirimleri',
    'bes_iptal_bildirimleri',
    'sendika_istifa_bildirimleri'
  ]
  loop
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl and policyname = tbl || '_select'
    ) then
      execute format(
        'create policy %I on public.%I for select to authenticated using (
          public.is_admin_like(auth.uid())
          or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
          or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
        )',
        tbl || '_select', tbl
      );
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl and policyname = tbl || '_insert'
    ) then
      execute format(
        'create policy %I on public.%I for insert to authenticated with check (
          public.is_admin_like(auth.uid())
          or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
          or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
        )',
        tbl || '_insert', tbl
      );
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl and policyname = tbl || '_delete'
    ) then
      execute format(
        'create policy %I on public.%I for delete to authenticated using (
          public.is_admin_like(auth.uid())
          or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
        )',
        tbl || '_delete', tbl
      );
    end if;
  end loop;
end
$$;
