create table if not exists public.performans_programi_veri_giris (
  id bigint generated by default as identity primary key,
  gosterge_id bigint not null references public.stratejik_plan_gosterge(id) on delete cascade,
  faaliyet_id bigint not null references public.stratejik_plan_faaliyet(id) on delete cascade,
  yil integer not null check (yil >= 1900 and yil <= 2500),
  mudurluk text not null,
  planlanan_cari_yil numeric null,
  gerceklesme_tahmini_cari_yil numeric null,
  gosterge_aciklama text null,
  hesaplama_yontemi text null,
  updated_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (gosterge_id, yil, mudurluk)
);

create index if not exists performans_programi_veri_giris_faaliyet_idx
  on public.performans_programi_veri_giris (faaliyet_id, yil);

create or replace function public.set_updated_at_performans_programi_veri_giris()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_performans_programi_veri_giris_updated_at
  on public.performans_programi_veri_giris;

create trigger trg_performans_programi_veri_giris_updated_at
before update on public.performans_programi_veri_giris
for each row execute function public.set_updated_at_performans_programi_veri_giris();

alter table public.performans_programi_veri_giris enable row level security;

drop policy if exists "pp_veri_giris_select_auth" on public.performans_programi_veri_giris;
create policy "pp_veri_giris_select_auth"
  on public.performans_programi_veri_giris for select to authenticated
  using (true);

drop policy if exists "pp_veri_giris_insert_auth" on public.performans_programi_veri_giris;
create policy "pp_veri_giris_insert_auth"
  on public.performans_programi_veri_giris for insert to authenticated
  with check (true);

drop policy if exists "pp_veri_giris_update_auth" on public.performans_programi_veri_giris;
create policy "pp_veri_giris_update_auth"
  on public.performans_programi_veri_giris for update to authenticated
  using (true)
  with check (true);

drop policy if exists "pp_veri_giris_delete_auth" on public.performans_programi_veri_giris;
create policy "pp_veri_giris_delete_auth"
  on public.performans_programi_veri_giris for delete to authenticated
  using (true);
