-- Tanımlar > Hareket Tanımları (Geliş/Gidiş türü + serbest tip metni)

CREATE TABLE IF NOT EXISTS public.tanim_hareket_tanim (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sira_no integer,
  tur text NOT NULL CHECK (tur IN ('Geliş', 'Gidiş')),
  tip text NOT NULL,
  aktif boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tanim_hareket_tanim_sira ON public.tanim_hareket_tanim (sira_no);
CREATE INDEX IF NOT EXISTS idx_tanim_hareket_tanim_tur ON public.tanim_hareket_tanim (tur);

COMMENT ON TABLE public.tanim_hareket_tanim IS 'Tanımlar > Hareket Tanımları: tür (Geliş/Gidiş) ve tip metni.';

ALTER TABLE public.tanim_hareket_tanim ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "authenticated_full_access" ON public.tanim_hareket_tanim;
CREATE POLICY "authenticated_full_access" ON public.tanim_hareket_tanim
  FOR ALL USING (auth.role() = 'authenticated');
