-- Bildirim · Mehil İzni ve Harcırah Talep bildirimleri

create table if not exists public.mehil_izni_bildirimleri (
  id bigint generated by default as identity primary key,
  sicil_no text not null,
  ad_soyad text not null,
  tckn text null,
  geldigi_kurum text not null,
  nakil_tarihi date not null,
  mehil_baslangic_tarihi date not null,
  mehil_bitis_tarihi date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  created_by_email text null
);

comment on table public.mehil_izni_bildirimleri is
  'Mehil izni bildirimi kayıtları; yalnızca memur statüsündeki personel.';

create index if not exists idx_mehil_izni_sicil on public.mehil_izni_bildirimleri (sicil_no);
create index if not exists idx_mehil_izni_created on public.mehil_izni_bildirimleri (created_at desc);

alter table public.mehil_izni_bildirimleri enable row level security;

create table if not exists public.harcirah_talep_bildirimleri (
  id bigint generated by default as identity primary key,
  sicil_no text not null,
  ad_soyad text not null,
  tckn text null,
  adres text null,
  geldigi_kurum text not null,
  nakil_tarihi date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  created_by_email text null
);

comment on table public.harcirah_talep_bildirimleri is
  'Harcırah talep bildirimi kayıtları; yalnızca memur statüsündeki personel.';

create index if not exists idx_harcirah_talep_sicil on public.harcirah_talep_bildirimleri (sicil_no);
create index if not exists idx_harcirah_talep_created on public.harcirah_talep_bildirimleri (created_at desc);

alter table public.harcirah_talep_bildirimleri enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'mehil_izni_bildirimleri'
      and policyname = 'mehil_izni_bildirimleri_select'
  ) then
    create policy mehil_izni_bildirimleri_select
    on public.mehil_izni_bildirimleri
    for select
    to authenticated
    using (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'mehil_izni_bildirimleri'
      and policyname = 'mehil_izni_bildirimleri_insert'
  ) then
    create policy mehil_izni_bildirimleri_insert
    on public.mehil_izni_bildirimleri
    for insert
    to authenticated
    with check (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'mehil_izni_bildirimleri'
      and policyname = 'mehil_izni_bildirimleri_update'
  ) then
    create policy mehil_izni_bildirimleri_update
    on public.mehil_izni_bildirimleri
    for update
    to authenticated
    using (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    )
    with check (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'mehil_izni_bildirimleri'
      and policyname = 'mehil_izni_bildirimleri_delete'
  ) then
    create policy mehil_izni_bildirimleri_delete
    on public.mehil_izni_bildirimleri
    for delete
    to authenticated
    using (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'harcirah_talep_bildirimleri'
      and policyname = 'harcirah_talep_bildirimleri_select'
  ) then
    create policy harcirah_talep_bildirimleri_select
    on public.harcirah_talep_bildirimleri
    for select
    to authenticated
    using (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'harcirah_talep_bildirimleri'
      and policyname = 'harcirah_talep_bildirimleri_insert'
  ) then
    create policy harcirah_talep_bildirimleri_insert
    on public.harcirah_talep_bildirimleri
    for insert
    to authenticated
    with check (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'harcirah_talep_bildirimleri'
      and policyname = 'harcirah_talep_bildirimleri_update'
  ) then
    create policy harcirah_talep_bildirimleri_update
    on public.harcirah_talep_bildirimleri
    for update
    to authenticated
    using (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    )
    with check (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'harcirah_talep_bildirimleri'
      and policyname = 'harcirah_talep_bildirimleri_delete'
  ) then
    create policy harcirah_talep_bildirimleri_delete
    on public.harcirah_talep_bildirimleri
    for delete
    to authenticated
    using (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;
end
$$;
