-- Bildirim · Hizmet Birleştirme işlemleri (SGK dilekçe form kayıtları)

create table if not exists public.hizmet_birlestirme_islemleri (
  id bigint generated by default as identity primary key,
  sicil_no text null,
  ad_soyad text not null,
  tckn text null,
  personel_durum text not null default 'calisan'
    check (personel_durum in ('calisan', 'ayrilan')),
  emeklilik_sicil_no text null,
  ssk text null,
  bagkur_sicil_no text null,
  hizmet_illeri text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  created_by_email text null
);

comment on table public.hizmet_birlestirme_islemleri is
  'Hizmet birleştirme (SGK) dilekçe formu kayıtları; çalışan veya ayrılan personel.';

create index if not exists idx_hizmet_birlestirme_sicil
  on public.hizmet_birlestirme_islemleri (sicil_no);
create index if not exists idx_hizmet_birlestirme_created
  on public.hizmet_birlestirme_islemleri (created_at desc);

alter table public.hizmet_birlestirme_islemleri enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'hizmet_birlestirme_islemleri'
      and policyname = 'hizmet_birlestirme_islemleri_select'
  ) then
    create policy hizmet_birlestirme_islemleri_select
    on public.hizmet_birlestirme_islemleri
    for select
    to authenticated
    using (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'hizmet_birlestirme_islemleri'
      and policyname = 'hizmet_birlestirme_islemleri_insert'
  ) then
    create policy hizmet_birlestirme_islemleri_insert
    on public.hizmet_birlestirme_islemleri
    for insert
    to authenticated
    with check (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'hizmet_birlestirme_islemleri'
      and policyname = 'hizmet_birlestirme_islemleri_update'
  ) then
    create policy hizmet_birlestirme_islemleri_update
    on public.hizmet_birlestirme_islemleri
    for update
    to authenticated
    using (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    )
    with check (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
      or sicil_no in (select ap.sicil_no from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'hizmet_birlestirme_islemleri'
      and policyname = 'hizmet_birlestirme_islemleri_delete'
  ) then
    create policy hizmet_birlestirme_islemleri_delete
    on public.hizmet_birlestirme_islemleri
    for delete
    to authenticated
    using (
      public.is_admin_like(auth.uid())
      or not exists (select 1 from public.app_profiles ap where ap.id = auth.uid())
    );
  end if;
end
$$;
