create table if not exists public.performans_programi_program (
  id bigint generated by default as identity primary key,
  yil integer not null check (yil >= 1900 and yil <= 2500),
  sira_no integer null check (sira_no > 0),
  kodu text not null,
  program_adi text not null,
  aktif boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists performans_programi_program_yil_idx
  on public.performans_programi_program (yil);

create or replace function public.set_updated_at_performans_programi_program()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_performans_programi_program_updated_at
  on public.performans_programi_program;

create trigger trg_performans_programi_program_updated_at
before update on public.performans_programi_program
for each row execute function public.set_updated_at_performans_programi_program();

alter table public.performans_programi_program enable row level security;

drop policy if exists "performans_programi_program_select_auth"
  on public.performans_programi_program;
create policy "performans_programi_program_select_auth"
  on public.performans_programi_program
  for select to authenticated
  using (true);

drop policy if exists "performans_programi_program_insert_auth"
  on public.performans_programi_program;
create policy "performans_programi_program_insert_auth"
  on public.performans_programi_program
  for insert to authenticated
  with check (true);

drop policy if exists "performans_programi_program_update_auth"
  on public.performans_programi_program;
create policy "performans_programi_program_update_auth"
  on public.performans_programi_program
  for update to authenticated
  using (true)
  with check (true);

drop policy if exists "performans_programi_program_delete_auth"
  on public.performans_programi_program;
create policy "performans_programi_program_delete_auth"
  on public.performans_programi_program
  for delete to authenticated
  using (true);
